/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.18 Marie_Miku_terreSSGLB.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/Marie_Miku_terreSSGLB.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Sphere002" geometry={nodes.Sphere002.geometry} material={materials['Material.001']}>
          <mesh name="Cube" geometry={nodes.Cube.geometry} material={materials['Material.001']} position={[0, 3.348, 0]} />
          <mesh name="Circle001" geometry={nodes.Circle001.geometry} material={materials['Material.001']} position={[0, 1.652, 0.064]} />
        </mesh>
        <mesh name="Circle" geometry={nodes.Circle.geometry} material={materials['Material.001']} position={[0, 1.652, 0.064]}>
          <mesh name="Star001" geometry={nodes.Star001.geometry} material={materials['Material.001']} position={[0.002, 3.336, -0.064]} rotation={[0, -0.031, 0]} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/Marie_Miku_terreSSGLB.glb')
