/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.17 Marie_Miku_DiamondAndStarGLB.glb 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./Marie_Miku_DiamondAndStarGLB.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Star" rotation={[Math.PI / 2, -0.08, 0]} />
        <mesh name="Vaisseau" geometry={nodes.Vaisseau.geometry} material={materials.etoile} rotation={[-Math.PI / 2, 0, 0]} scale={2.255} />
      </group>
    </group>
  )
}

useGLTF.preload('./Marie_Miku_DiamondAndStarGLB.glb')
